//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSlicer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\..\\\\..\\\\TestEngineStub\\\\bin\\\\Debug\\\\TestEngineStub.exe")]
        public string SlicingEnginePath {
            get {
                return ((string)(this["SlicingEnginePath"]));
            }
            set {
                this["SlicingEnginePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{APPDATA}\\LSlicer\\Resources")]
        public string SlicingParametersRepoPath {
            get {
                return ((string)(this["SlicingParametersRepoPath"]));
            }
            set {
                this["SlicingParametersRepoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{APPDATA}\\LSlicer\\Temp\\")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
            set {
                this["WorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\..\\\\..\\\\TestEngineStub\\\\slicing_d_parameters.json")]
        public string DefaultSlicingParameters {
            get {
                return ((string)(this["DefaultSlicingParameters"]));
            }
            set {
                this["DefaultSlicingParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{APPDATA}\\LSlicer\\Jobs\\")]
        public string SlicingResultDirectory {
            get {
                return ((string)(this["SlicingResultDirectory"]));
            }
            set {
                this["SlicingResultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\..\\\\..\\\\SupportEngine\\\\bin\\\\x64\\\\Debug\\\\SupportEngine.exe")]
        public string SupportEnginePath {
            get {
                return ((string)(this["SupportEnginePath"]));
            }
            set {
                this["SupportEnginePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\..\\\\..\\\\TestEngineStub\\\\support_d_parameters.json")]
        public string DefaultSupportParameters {
            get {
                return ((string)(this["DefaultSupportParameters"]));
            }
            set {
                this["DefaultSupportParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{APPDATA}\\LSlicer\\Resources")]
        public string SupportParametersRepoPath {
            get {
                return ((string)(this["SupportParametersRepoPath"]));
            }
            set {
                this["SupportParametersRepoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomSupportGenerator;Cura;")]
        public string SupportEngineList {
            get {
                return ((string)(this["SupportEngineList"]));
            }
            set {
                this["SupportEngineList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomSupportGenerator")]
        public string SelectedSupportEngine {
            get {
                return ((string)(this["SelectedSupportEngine"]));
            }
            set {
                this["SelectedSupportEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomSliceGenerator;Cura;")]
        public string SliceEngineList {
            get {
                return ((string)(this["SliceEngineList"]));
            }
            set {
                this["SliceEngineList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomSliceGenerator")]
        public string SelectedSliceEngine {
            get {
                return ((string)(this["SelectedSliceEngine"]));
            }
            set {
                this["SelectedSliceEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{APPDATA}\\LSlicer\\Temp\\current_changes_file")]
        public string CurrentChangesPath {
            get {
                return ((string)(this["CurrentChangesPath"]));
            }
            set {
                this["CurrentChangesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:20")]
        public global::System.TimeSpan AutoSaveInterval {
            get {
                return ((global::System.TimeSpan)(this["AutoSaveInterval"]));
            }
            set {
                this["AutoSaveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:00")]
        public global::System.TimeSpan WaitingUserActionTimeout {
            get {
                return ((global::System.TimeSpan)(this["WaitingUserActionTimeout"]));
            }
            set {
                this["WaitingUserActionTimeout"] = value;
            }
        }
    }
}
