// <auto-generated />
namespace LSlicer.Implementations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addChangesSaving : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addChangesSaving));
        
        string IMigrationMetadata.Id
        {
            get { return "202010181802246_addChangesSaving"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
